name: serundeputy-fe
proxy:
  appserver:
    - serundeputy-fe.lndo.site
env_file:
  - .env
services:
  appserver:
    type: node:10
    command: cp -n /app/.env.example /app/.env && yarn dev --hostname 0.0.0.0 --port 80
    install_dependencies_as_me:
      - yarn install
tooling:
  yarn:
    service: appserver
  npm:
    service: appserver
  node:
    service: appserver
  nuxt:
    cmd: /app/node_modules/.bin/nuxt
    service: appserver
