name: serundeputyfrontend
proxy:
  appserver:
    - serundeputy-frontend.lndo.site
services:
  appserver:
    type: node:10
    command: cp -n /app/.env.example /app/.env && "yarn dev --hostname 0.0.0.0 --port 3333"
    install_dependencies_as_me:
      - yarn install
tooling:
  yarn:
    service: appserver
  npm:
    service: appserver
  node:
    service: appserver
  nuxt:
    cmd: /app/node_modules/.bin/nuxt
    service: appserver
